server {
    listen 80;
    # 1. Σερβίρει το React Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            # Αυτό λύνει το πρόβλημα του React Router (ώστε να μη βγάζει 404 αν κάνεις refresh)
            try_files $uri $uri/ /index.html;
        }

    # 2. Reverse Proxy για το Backend (Το μαγικό βήμα για το K8s)
        location /api/ {
            # Το Nginx (μέσα στο pod) μιλάει με το K8s Service 'repo-analyzer'
            # ΠΡΟΣΟΧΗ: Το / στο τέλος είναι σημαντικό!
            # Αφαιρεί το '/api/' και στέλνει το υπόλοιπο στη Java.
            proxy_pass http://repo-analyzer:8080/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
}